### PR TITLE
feat: add selectedLineBgColor theme customization

### PR DESCRIPTION
**Pull request by tiagovla**
#393

### CODE REVIEW

**Comment by zolrath** [comment]
Would love to see this, the default color is hard to read with my theme and was easily corrected in lazygit!

**Comment by mark2185** [comment]
@yshadow thanks for bringing this up, someone will take a look at this.

In the meantime, have you tried building from source?

**Comment by yshadow** [comment]
No, not yet. Just a minute ago found the config for lazydocker and this PR

**Comment by yshadow** [comment]
yes it works 👍🏻

**Comment by yshadow** [comment]
image

**Comment by dotfrag** [comment]
Bump. Can we please have this merged soon? I'm having trouble using lazydocker on my machines mainly because of this.

**Comment by jesseduffield** [comment]
LGM, sorry for the wait!

**Pull request merged**
