### PR TITLE
Fix AUR link in docs

### PR DESCRIPTION
**Pull request by conorbros**

### CODE REVIEW

**Comment by mjarkk** [comment]
Hmm maybe we should simplify the arch section because most people who use arch probably know how to install a package from the AUR.

```md
### Arch Linux AUR

You can install [lazydocker from the AUR](https://aur.archlinux.org/packages/lazydocker)
```

Also the arch section is now a bit confusing as it gives the impression there is a different package for the development version while the url points to the same package as installed in the example above it

**Comment by conorbros** [comment]
Fair enough, I just wanted something to grab and copy paste.

**Comment by mjarkk** [comment]
Maybe we can include the yay example as it's a commonly used package manager for arch

**Comment by conorbros** [comment]
Sounds good to me. I think most Arch users would be happy with the yay example

**Comment by mjarkk** [comment]
Thanks

**Pull request merged**
