### PR TITLE
Use xdg package instead of configdir

### PR DESCRIPTION
**Pull request by dawidd6**
Closes: #125 

@michaelrigart if you could test it.

### CODE REVIEW

**Comment by michaelrigart** [comment]
Hi @dawidd6 

Thank you for the update. What are the build steps I can execute to build the xdg branch on macos?

**Comment by dawidd6** [comment]
```sh
git clone https://github.com/jesseduffield/lazydocker
cd lazydocker
git checkout xdg
go build -mod=vendor
```

**Comment by michaelrigart** [comment]
@dawidd6 : thank you for the info.

build succeeded and I can confirm the config and log are now written to  ~/.config/jesseduffield/lazydocker and no longer to ~/Library/Application Support

**Comment by dawidd6** [comment]
@michaelrigart thanks for testing!

It's merge time I guess.

**Pull request merged**
