### PR TITLE
improve readability of colours

### PR DESCRIPTION
**Pull request by jesseduffield**
fixes https://github.com/jesseduffield/lazydocker/issues/63

### CODE REVIEW

**Comment by mjarkk** [comment]
Isn't is a good idea to make this user configurable?

**Comment by jesseduffield** [comment]
You're probably right. I just wonder how configurable we want to go. Do we say want something like:
```
gui:
  theme:
    servicePanel:
      status:
        none: blue
        running: green
        exitedZero: yellow
        exitedNonZero: red
```

**Comment by mjarkk** [comment]
Looks good to me.  
For the people that bother changing the colors they probably want to have full control over all colors so would not be a bad idea to give them full access to all colors.

**Comment by jesseduffield** [comment]
agreed. I think I'll merge this PR, which will fix the immediate issue, then put up an issue to allow full customisation of colours

**Pull request merged**
