### PR TITLE
Docker SDK update

### PR DESCRIPTION
**Pull request by dawidd6**
This should theoretically close: #64 

I updated the Docker SDK used in lazydocker from `v1.13.1` (which was released in Feb 8, 2017) to `v0.7.3-0.20190307005417-54dddadc7d5d`. Also specified the minimum Docker API version supported to `1.20`.

Why not a normal tag, but a commit?
Well, cause when one would have a look at https://github.com/moby/moby then one would see that the latest tag was pushed on Jun 28, 2017.
So, this PR is simply bumping Docker dependency to `54dddadc7d5d` commit.

Why this commit specifically?
I just use it in my project and it works well, so thought it might be okay to use it here as well.

---

**Note for myself**: update README requirements section, when this is merged.

### CODE REVIEW

**Comment by jesseduffield** [comment]
LGTM. I'm guessing all those extra lines are just a reflection of how that package has grown over time? Also have you done a quick test of lazydocker's basic functionality to check that nothing was broken by this change?

**Comment by dawidd6** [comment]
That's right, they must have changed something.

Yes, I did some testing, seems to be ok.

**Comment by jesseduffield** [comment]
sounds good :)

**Comment by dawidd6** [comment]
So, I roughly tested it with Docker in Docker image, cause I couldn't find a better way to install older version of Docker and it seems to work, but I think we can wait for @warmchang to test it on his machine.

**Comment by warmchang** [comment]
FYI: https://github.com/jesseduffield/lazydocker/issues/64#issuecomment-509049007

**Comment by jesseduffield** [comment]
Looks like we can merge this then, you just need to resolve conflicts @dawidd6

**Comment by dawidd6** [comment]
Yep. Will do later today.

**Pull request merged**
