### PR TITLE
Bump version tag in installation docs for asdf

### PR DESCRIPTION
**Pull request by helgeblod**
- Latest version is 0.21.1
- Update asdf install instructions to reflect latest version

### CODE REVIEW

**Comment by jesseduffield** [comment]
Is it possible to use a 'latest' tag?

**Comment by helgeblod** [comment]
Yes, that's even better. I'll update the PR 👍

**Comment by helgeblod** [comment]
Updated the PR to use `latest` tag in asdf and confirmed that it works 👍

**Comment by jesseduffield** [comment]
Thanks for making this

**Pull request merged**
