### PR TITLE
Add automated install-update steps for Linux

### PR DESCRIPTION
**Pull request by immanuelfodor**
Hi, I've added a small code snippet to be able to download and install/update the binary file without manual steps. Tested on Ubuntu and Manjaro Linux distros. Also improved the clickability of the release link.

### CODE REVIEW

**Comment by dawidd6** [comment]
This, to be fully automated would need to be in form of a script in file, so one could just pipe curl to bash (which isn't that good idea).

What I'm trying to say is that, if you really want to make this right, you should put theses commands in file and store it in https://github.com/jesseduffield/lazydocker/tree/master/scripts (probably). Then in README, you can write, that user should execute: `curl url_to_raw_script | bash`, to get the latest release.

**Comment by immanuelfodor** [comment]
I'm not really a fan of piping into bash, to be honest.  
Should I create the script anyway, or we just call it semi-automatic way? :grinning:

**Comment by dawidd6** [comment]
Well, the script anyway would be present in repository, so everyone interested would have the possibility to review it thoroughly before piping it to bash. Also the script seems to not be very complicated or long.

So, hmm, after all, I would vote for storing it in scripts/ directory.

**Comment by immanuelfodor** [comment]
Okay, I think this is it.

**Comment by immanuelfodor** [comment]
I've just seen the version check part: the `mv -f` command always rewrites the installed version, so you can use it to install or update the existing binary file.

**Comment by immanuelfodor** [comment]
@jesseduffield what do you think, are we ready to merge? :)

**Comment by jesseduffield** [comment]
Thanks for making this! I'm satisfied, what about you @dawidd6 ?

**Comment by dawidd6** [comment]
@jesseduffield yep, should be fine.

**Comment by jesseduffield** [comment]
mergin!

**Pull request merged**
