### PR TITLE
go.mod: github.com/docker/docker, docker/cli v27.0.3

### PR DESCRIPTION
**Pull request by thaJeztah**
### Dockerfile: fix alpine version

The go1.20 image is not published with alpine 3.15; updating the version.

### go.mod: github.com/sirupsen/logrus v1.9.3

update to the current version, which addresses some issues with current
Go versions, and removes the legacy konsorten/go-windows-terminal-sequences
dependency.

### go.mod: github.com/imdario/mergo v0.3.16

update to the last version of the module under the old name, before v1.0.0
renames the module.

### go.mod: github.com/morikuni/aec v1.0.0

no changes, but using the tagged version

### go.mod: github.com/moby/term v0.5.0

no changes, but using the tagged version

### go.mod: github.com/docker/go-units v0.5.0

removes uses of regular expressions

### go.mod: golang.org/x/time v0.5.0

no changes, but using the tagged version

### go.mod: github.com/Microsoft/go-winio v0.5.3

update to a version compatible with go1.22 and up

### go.mod: github.com/docker/docker, docker/cli v23.0.6

Update to v23.0, and remove uses of deprecated types.

### go.mod: github.com/docker/docker, docker/cli v24.0.7

Update to v24.0, and remove uses of deprecated types.

### go.mod: github.com/docker/go-connections v0.5.0

drops support for legacy Go versions, add support for TLS 1.3

### go.mod: github.com/docker/docker, docker/cli v25.0.5

Update to v25.0, and remove uses of deprecated types.

### go.mod: github.com/docker/docker, docker/cli v26.1.4

Update to v26.1, and remove uses of deprecated types.

### go.mod: github.com/docker/docker, docker/cli v27.0.3

Update to v27.0, and remove uses of deprecated types.

### CODE REVIEW

**Comment by jesseduffield** [comment]
I've just given this a test and it worked fine. Thanks for putting the effort into this @thaJeztah .

Also, I'd like to commend you on your maintainership of docker (and related repos): whenever I read your comments on issues you're always being thoughtful and reasonable, so kudos.

**Comment by thaJeztah** [comment]
Sorry for the late reply (busy week); Thank you! And thanks for reviewing!

I'm not a Lazydocker user myself, but I frequently hear about people who are.  I arrived here following https://github.com/basecamp/omakub/pull/83#issuecomment-2227268206, which made me curious if I could see something obvious what could cause issues. I didn't see anything that stood out immediately, but saw the version of the dependencies were somewhat behind, and knew we had a couple of types being moved to different locations, so thought; let me give that a try 😄)

**Comment by thaJeztah** [comment]
Actually; I saw this was not released yet; let me update this to v27.1.1; shouldn't really affect this codebase, but we issued a CVE that may cause it to be flagged by scanners;

- https://github.com/jesseduffield/lazydocker/pull/568

**Pull request merged**
