### PR TITLE
Update keybindings.go

### PR DESCRIPTION
**Pull request by Tuurlijk**
Remove duplicate keybinding: volumes - c
Bind F10 to gui.quit

### CODE REVIEW

**Comment by dawidd6** [comment]
Nice, but why F10 tho?

**Comment by Tuurlijk** [comment]
Muscle memory from the Norton Commander / Midnight Commander days

**Comment by glvr182** [comment]
I would say that this can be done by the users themselfs when #117 is merged. No need to make this into a hardcoded config

**Comment by Tuurlijk** [comment]
Ok, but remove the duplicate volume - c keybinding.

**Comment by dawidd6** [comment]
Can you make another commit removing this new binding? @Tuurlijk

**Comment by glvr182** [comment]
> Ok, but remove the duplicate volume - c keybinding.

Yea I removed that in the PR.

**Pull request merged**
