### PR TITLE
Bump alpine version to 3.17

### PR DESCRIPTION
**Pull request by biran4454**
Prevent docker build error (armv8) as Golang haven't released an alpine 3.15 version on 1.20.

### CODE REVIEW

**Comment by turbcool** [comment]
Tested this on an `arm64v8` device. The image builds successfully (following the README instructions).

**Comment by mark2185** [comment]
This PR should close #497 .

**Comment by cwong-archy** [comment]
i am having trouble building with this change -
```
──── git diff
diff --git a/Dockerfile b/Dockerfile
index 9719593..502093c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,5 @@
 ARG BASE_IMAGE_BUILDER=golang
-ARG ALPINE_VERSION=3.15
+ARG ALPINE_VERSION=3.17
 ARG GO_VERSION=1.20

 FROM ${BASE_IMAGE_BUILDER}:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder
```

```
──── docker build -t lazyteam/lazydocker --build-arg BASE_IMAGE_BUILDER=arm64v8/golang --build-arg GOARCH=arm64 https://github.com/jesseduffield/lazydocker.git
[+] Building 5.3s (3/3) FINISHED                                                                                                                                                                     docker:default
 => CACHED [internal] load git source https://github.com/jesseduffield/lazydocker.git                                                                                                                          3.6s
 => ERROR [internal] load metadata for docker.io/arm64v8/golang:1.20-alpine3.15                                                                                                                                1.5s
 => [auth] arm64v8/golang:pull token for registry-1.docker.io                                                                                                                                                  0.0s
------
 > [internal] load metadata for docker.io/arm64v8/golang:1.20-alpine3.15:
------
Dockerfile:19
--------------------
  17 |         -X main.buildSource=Docker"
  18 |
  19 | >>> FROM ${BASE_IMAGE_BUILDER}:${GO_VERSION}-alpine${ALPINE_VERSION} AS docker-builder
  20 |     ARG GOARCH=amd64
  21 |     ARG GOARM
--------------------
ERROR: failed to solve: arm64v8/golang:1.20-alpine3.15: docker.io/arm64v8/golang:1.20-alpine3.15: not found
```

am i doing something wrong? i dont see any reference to 3.15 anywhere in the repo after the change but some how it still think its looking for alpine3.15 ...

**Comment by biran4454** [comment]
> ```
> ──── docker build -t lazyteam/lazydocker --build-arg BASE_IMAGE_BUILDER=arm64v8/golang --build-arg GOARCH=arm64 https://github.com/jesseduffield/lazydocker.git
> ```

Looks like you're still building from the main git repo rather than the forked / local one.

**Comment by cwong-archy** [comment]
> > ```
> > ──── docker build -t lazyteam/lazydocker --build-arg BASE_IMAGE_BUILDER=arm64v8/golang --build-arg GOARCH=arm64 https://github.com/jesseduffield/lazydocker.git
> > ```
> 
> Looks like you're still building from the main git repo rather than the forked / local one.

thank you!!! good catch!!! 😅

**Comment by cwong-archy** [comment]
> > > ```
> > > ──── docker build -t lazyteam/lazydocker --build-arg BASE_IMAGE_BUILDER=arm64v8/golang --build-arg GOARCH=arm64 https://github.com/jesseduffield/lazydocker.git
> > > ```
> > 
> > 
> > Looks like you're still building from the main git repo rather than the forked / local one.
> 
> thank you!!! good catch!!! 😅

@biran4454 appreciate the help. finally got it built. for raspberry pi (hopefully this will help others), i had to pass these values during build -
```
docker build -t lazyteam/lazydocker --build-arg BASE_IMAGE_BUILDER=arm32v7/golang --build-arg GOARCH=arm .
```

**Comment by jesseduffield** [comment]
This is obsoleted by https://github.com/jesseduffield/lazydocker/pull/561, closing

**Pull request closed without merging**
