### PR TITLE
Add -f compose file flag

### LINKED ISSUE #11: Support the docker-compose -f flag
In our app we have multiple docker-compose files, eg. for running the app locally, and then subsets for functional/integration tests with various different configuration/volume adjustments. It'd be awesome to be able to do `ld -f docker-compose-functional-test.yml` and have it run within the context of that file. Would something like that make sense?

### PR DESCRIPTION
**Pull request by mcintyre94**
Builds on #38 (first three commits are from there), closes #11 

Using Flaggy, adds the -f flag which allows specifying multiple docker-compose yml files which are passed into the `docker-compose` command. This allows lazydocker to support multiple arbitrary docker-compose files.

Also added some unit tests for this new code.

@markphip Does this address your use case too? :)

### CODE REVIEW

**Comment by markphip** [comment]
If I can do something like this then I would say yes:

`lazydocker -f docker-compose.yml -f docker-compose-srv1.yml -f docker-compose-srv2.yml`

I was able to successfully use a custom-compose script but this would be better for my workflow.

**Comment by mcintyre94** [comment]
That should be exactly what this adds :)


________________________________

**Comment by markphip** [comment]
Thanks I built this PR locally and confirmed it works nicely.

**Comment by jesseduffield** [comment]
another fantastic PR, and thanks for adding the tests! mergin

**Pull request merged**
